version: '3.8'

services:
  dbpagamento:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=mydatabase
    volumes:
      - dbpagamento_data:/var/lib/mysql

  dbcliente:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"

  dbpedido:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydatabase
    ports:
      - "3307:3306"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  pagamento:
    build:
      context: ./src/Pagamento
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - dbpagamento
    environment:
      - DATABASE_HOST=dbpagamento
      - DATABASE_USER=root
      - DATABASE_PASSWORD=my-secret-pw
      - DATABASE_NAME=mydatabase

  cliente:
    build:
      context: ./src/Cliente
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - dbcliente
    environment:
      - DATABASE_HOST=dbcliente
      - DATABASE_USER=root
      - DATABASE_PASSWORD=my-secret-pw
      - DATABASE_NAME=mydatabase

  pedido:
    build:
      context: ./src/Pedido
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - dbpedido
    environment:
      - DATABASE_HOST=dbpedido
      - DATABASE_USER=root
      - DATABASE_PASSWORD=my-secret-pw
      - DATABASE_NAME=mydatabase


volumes:
  dbpagamento_data: