version: '3.8'

services:
  db_pagamento:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: db_pagamento
    ports:
      - "3307:3306"

  db_cliente:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: db_cliente
    ports:
      - "3308:3306"

  db_pedido:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: db_pedido
    ports:
      - "3309:3306"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  pagamento:
    build:
      context: ./src/Pagamento
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

  cliente:
    build:
      context: ./src/Cliente
      dockerfile: Dockerfile
    ports:
      - "8082:8080"

  pedido:
    build:
      context: ./src/Pedido
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
