scrape_configs:
  - job_name: 'spring_app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['pagamento:8081']
      - targets: ['cliente:8082']
      - targets: ['pedido:8083']